### ISSUE TITLE
Loading by URL direct to a Remote via Host throws error

### ISSUE THREAD

**Issue by Coly010** [module-federation/node#3]
Having both Host and Remote applications running, when trying to navigate directly to a URL on the Host that uses a Remote creates the following error

```
needs to load remote module from remote1

remotes known to remote1 {}

undefined:493
/******/                                                                Object.assign(global.__remote_scope__._config, remotes)
                                                                                                              ^

TypeError: Cannot read properties of undefined (reading '_config')
    at eval (eval at <anonymous> (/Users/columferry/dev/nrwl/spike/nx-angular-mf-ssr/dist/apps/shell/server/main.js:819:20), <anonymous>:493:56)
    at new ZoneAwarePromise (/Users/columferry/dev/nrwl/spike/nx-angular-mf-ssr/dist/apps/shell/server/main.js:98368:21)
    at Object.__webpack_require__.f.readFileVm (eval at <anonymous> (/Users/columferry/dev/nrwl/spike/nx-angular-mf-ssr/dist/apps/shell/server/main.js:819:20), <anonymous>:433:30)
    at eval (eval at <anonymous> (/Users/columferry/dev/nrwl/spike/nx-angular-mf-ssr/dist/apps/shell/server/main.js:819:20), <anonymous>:98:40)
    at Array.reduce (<anonymous>)
    at Function.__webpack_require__.e (eval at <anonymous> (/Users/columferry/dev/nrwl/spike/nx-angular-mf-ssr/dist/apps/shell/server/main.js:819:20), <anonymous>:97:67)
    at Object../Module (eval at <anonymous> (/Users/columferry/dev/nrwl/spike/nx-angular-mf-ssr/dist/apps/shell/server/main.js:819:20), <anonymous>:14:30)
    at Object.get (eval at <anonymous> (/Users/columferry/dev/nrwl/spike/nx-angular-mf-ssr/dist/apps/shell/server/main.js:819:20), <anonymous>:21:23)
    at /Users/columferry/dev/nrwl/spike/nx-angular-mf-ssr/dist/apps/shell/server/main.js:731:37
    at Generator.next (<anonymous>)

A server error has occurred.
node exited with 1 code.
```
Test repo is: https://github.com/Coly010/nx-angular-mf-ssr/tree/use-mf-node-plugin

The part setting up the webpack config is here: https://github.com/Coly010/nx-angular-mf-ssr/blob/use-mf-node-plugin/libs/webpack-mf/src/lib/with-module-federation.ts#L305

## Steps
1. Clone the repo
2. Run `yarn install`
3. Have two terminal windows open
4. Run `nx serve-ssr shell` in one
5. Run `nx serve-ssr remote1` in the other
6. Open a browser at `localhost:4200/remote1`

## Info

From some minor investigation, it seems to be the remote is trying to use it's own name to discover if there any remotes, rather than the host trying to find the remote based on it's name

**Comment by ScriptedAlchemy** [comment]
NodeFederationPlugin replaces the target: node across the board. The host defines remote scope, remotes read their urls from the host since they only know their name and url is determined by consumer
